services:
  - type: web
    name: griffith-api
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: griffith-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
